### ISSUE TITLE
guru.nidi.graphviz.engine.GraphvizException: [dot.exe, dot.bat, dot.cmd] command not found

### ISSUE THREAD

**Issue by ca-stefan-cordes** [obscure1910/flow-landscape#1]
Tried your plugin but it fails with
guru.nidi.graphviz.engine.GraphvizException: [dot.exe, dot.bat, dot.cmd] command not found
on our Jenkins.

Our Jenkins itself can find the installed dot.exe as JENKINS/....job/.../depgraph-view/ is working.

It is not in the path but in Jenkins:
<img width="310" alt="image" src="https://github.com/obscure1910/flow-landscape/assets/50696194/ef7616ea-8962-4d76-9fef-c563009f1b44">

Do you need it in path?
Is there a config parameter to set path to dot.exe?

**Comment by obscure1910** [comment]
You do not need to have Graphviz installed. This exception is logged at INFO level:
`[INFO] Could not initialize guru.nidi.graphviz.engine.GraphvizCmdLineEngine
guru.nidi.graphviz.engine.GraphvizException: [dot.exe, dot.bat, dot.cmd] command not found
[INFO] Starting V8 runtime...
[INFO] Started V8 runtime. Initializing javascript...
[INFO] Initialized javascript.`

**Comment by ca-stefan-cordes** [comment]
You are right, it is working:

` <imageOutputDirectory>${project.build.directory}/site/flowlandscape/</imageOutputDirectory>`
creates site image with
flowlandscape/flowlandscape.png

(I previously searched for flowlandscape/index.html and so guessed the dot.exe message did cause the 404 on the site)

Additionally it was not clear the plugin worked es expected as the log ends with

```
11:09:36  [INFO] Could not initialize guru.nidi.graphviz.engine.GraphvizCmdLineEngine
11:09:36  guru.nidi.graphviz.engine.GraphvizException: [dot.exe, dot.bat, dot.cmd] command not found
11:09:36  [INFO] Starting V8 runtime...
11:09:36  [INFO] Started V8 runtime. Initializing javascript...
11:09:36  [INFO] Initialized javascript.
```

and I missed something like

`Successfully generated flowlandscape/flowlandscape.png `

or something similar.

**Comment by obscure1910** [comment]
Yes, the plugin should be more chatty. 
I have released a new version in which the GraphvizV8Engine is used as default. The error message is then gone. It will take a few days until it is available via maven.
