### ISSUE TITLE
LogbackServiceProvider has been compiled by a more recent version of the Java Runtime 

### ISSUE THREAD

**Issue by ca-stefan-cordes** [obscure1910/flow-landscape#5]
logback dependency should be 1.3.x because 
    <maven.compiler.target>1.8</maven.compiler.target>
is set in pom.xml

(class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by ca-stefan-cordes** [comment]
At least logback should be scope=provided to be able to take other slf4j implementation.

**Comment by obscure1910** [comment]
[https://github.com/obscure1910/flow-landscape/blob/bugfix/logback_version/pom.xml#L138](https://github.com/obscure1910/flow-landscape/blob/bugfix/logback_version/pom.xml#L138)

**Comment by obscure1910** [comment]
Fixed in version 1.1.8
